{{- if .Values.api.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "otel-demo.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "otel-demo.api.selectorLabels" . | nindent 4 }}
{{- end }}
