{{- if .Values.redis.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-demo.fullname" . }}-redis-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "otel-demo.redis.labels" . | nindent 4 }}
data:
  redis.conf: |
{{- .Values.redis.config | nindent 4 }}
{{- end }}
---
{{- if .Values.global.scenario }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otel-demo.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "otel-demo.labels" . | nindent 4 }}
data:
  scenario: {{ .Values.global.scenario | quote }}
  environment: {{ .Values.global.environment | quote }}
  otlp-endpoint: {{ include "otel-demo.otlpEndpoint" . | quote }}
  {{- if .Values.global.gitCommitSha }}
  git-commit-sha: {{ .Values.global.gitCommitSha | quote }}
  {{- end }}
  {{- if .Values.global.gitRepositoryUrl }}
  git-repository-url: {{ .Values.global.gitRepositoryUrl | quote }}
  {{- end }}
{{- end }}
